### ISSUE TITLE
Create a way to return to the site from the admin panel

### ISSUE THREAD

**Issue by TheBloodMan49** [InsaLan/backend-insalan.fr#109]
Currently we have a "see the site" button on the top-right that redirects to `api.insalan.fr/v1/` 
Maybe we can change that to `insalan.fr/`, and make it more visible ?

**Comment by KwikKill** [comment]
This is a good idea but unfortunately, that's handled by default django admin panel and it may not be possible.

**Comment by TheBloodMan49** [comment]
If I have some time I'll look into it, I posted this because I found it annoying that the button doesn't do it's job
