### ISSUE TITLE
PATCH user profile

### ISSUE THREAD

**Issue by KwikKill** [InsaLan/backend-insalan.fr#59]
For the frontend user dashboard page, we need to add a profile modification endpoint in the backend.
This endpoint must be a PATCH and could take a json containing the keys to change.
Possible keys are :
- Username
- Email
- Password

The current password must also be present to validate the request. 
Possible response could be :
- 200 (OK) : everything fine
- 400 (Bad Request) : password too weak, email invalid,...
- 401 (Unauthorized) : bad current password

**Comment by KwikKill** [comment]
@Lugrim there's an issue with password validation. The `validate_password` function raise an exception when password is not valid but this is not catched by the Backend and crash it.

Doc : https://docs.djangoproject.com/en/4.2/topics/auth/passwords/#django.contrib.auth.password_validation.validate_password

**Comment by Lugrim** [comment]
> Is this intended ?

It isn't, I added a fix and a test to avoid it happening again
