### ISSUE TITLE
Add a delete account endpoint

### ISSUE THREAD

**Issue by KwikKill** [InsaLan/backend-insalan.fr#63]
We have to add an endpoint that allow user to delete their account.
This endpoint could be a DELETE request with some kind of validation (could be password verification).

When a user is deleted, it should also delete their ongoing inscriptions (maybe automatic refund if possible), keep their past inscriptions (to keep events history).

We also need to check GDPR rules because if a user ask for an account deletion, we may not be able to keep his team history.

**Comment by Krakou** [comment]
Do we must keep deleted user still unique ? If not, why not make `ForeignKey.on_delete = SET_DEFAULT`, with default user a deleted user (with dummy data for example)

**Comment by ShiroUsagi-san** [comment]
I thought that was similar to what @Lugrim said but that's the easiest way to do this :ok_hand:

**Comment by Lugrim** [comment]
We should really ensure it doesn't break constrainsts

**Comment by Krakou** [comment]
For the moment : 
- `is_active` field is use nowhere
- `user` field from transaction model is already in `on_delete=models.SET_NULL`

Is there somewhere else where we have to keep an object if the user is deleted ? I have thought to : 

- Tournament, to keep the archives complete (in `Player`  and `Manager` models)
- Ticket

**Comment by KwikKill** [comment]
I'm closing this as I will be much easier to do it manually.
Having no control on account deletion is imo worst.
